name: Deploy Azure Functions (Python / Flex)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write   # required for OIDC
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: "${{ vars.AZURE_FUNCTIONAPP_NAME }}"   # set repo variable to your app name
  AZURE_FUNCTIONAPP_PROJECT_PATH: "."                            # project root

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Package (zip) artifact
        run: |
          zip -r functionapp.zip . -x ".git/*" ".github/*" "local.settings.json"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: functionapp
          path: .
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: functionapp.zip
